overrides: .nocover.yaml

package_module: community
packages:
  - community
  - activity
  - inactive_issues
  - data
  - gci
  - gsoc
  - gamification
  - log
  - meta_review
  - openhub
  - model
  - twitter
  - unassigned_issues

dependencies:
  - git+https://gitlab.com/coala/coala-utils.git
  - git-url-parse
  - django
  - django-distill
  - django-eventtools
  - git+https://gitlab.com/gitmate/open-source/IGitt.git@1fa5a0a21ea4fb8739d467c06972f748717adbdc
  - requests
  - python-dateutil
  - pillow
  - ruamel.yaml
  - markdown2
  - python_dateutil
  - PyGithub
  - xmltodict
  - termcolor

configuration:
  template_dir:
    - .moban.dt/
    - ../coala-mobans/templates/
    - ../coala-mobans/assets/
  configuration: .moban.yaml
  configuration_dir: ../coala-mobans/
targets:
  - .gitignore: community-gitignore.jj2
  - setup.cfg: setup.cfg.jj2
  - requirements.txt: requirements.txt.jj2
  - test-requirements.txt: community-test-requirements.txt.jj2
  - conftest.py: conftest.py
