overrides: .nocover.yaml

package_module: community
packages:
  - community
  - activity
  - inactive_issues
  - data
  - gci
  - gsoc
  - gamification
  - log
  - meta_review
  - openhub
  - model
  - twitter
  - unassigned_issues

dependencies:
  - git-url-parse
  - django
  - django-distill
  - django-eventtools
  - git+https://gitlab.com/jayvdb/IGitt.git@74a0141f3d77b8a51b6d964f9c64da67751e3762
  - requests
  - python-dateutil
  - pillow
  - ruamel.yaml
  - markdown2
  - python_dateutil
  - PyGithub
  - xmltodict

configuration:
  template_dir:
    - .moban.dt/
    - ../coala-mobans/templates/
    - ../coala-mobans/assets/
  configuration: .moban.yaml
  configuration_dir: ../coala-mobans/
targets:
  - .gitignore: community-gitignore.jj2
  - setup.cfg: setup.cfg.jj2
  - requirements.txt: requirements.txt.jj2
  - test-requirements.txt: community-test-requirements.txt.jj2
  - conftest.py: conftest.py
