# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('login', models.TextField(default=None, primary_key=True, serialize=False)),
                ('name', models.TextField(default=None, null=True)),
                ('bio', models.TextField(default=None, null=True)),
                ('num_commits', models.IntegerField(default=None, null=True)),
                ('reviews', models.IntegerField(default=None, null=True)),
                ('issues_opened', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
