# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-09 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180801_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='mergerequest',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
