# Generated by Django 2.1.5 on 2019-02-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180809_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='image_url',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
