# Generated by Django 2.1.7 on 2019-08-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180809_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='followers',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='location',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='public_gists',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='public_repos',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
