# Generated by Django 2.1.7 on 2019-08-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20190801_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='is_gci_participant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contributor',
            name='oauth_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contributor',
            name='statistics',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='type_of_issues_worked_on',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='updated_at',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='working_on_issues_count',
            field=models.TextField(default=None, null=True),
        ),
    ]
