# Generated by Django 2.1.7 on 2019-08-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20190802_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='increased_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='members_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
