# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-20 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.TextField(default=None, primary_key=True, serialize=False)),
                ('body', models.TextField(default=None, null=True)),
                ('diff', models.TextField(default=None, null=True)),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('last_edited_at', models.DateTimeField(default=None, null=True)),
                ('pos', models.IntegerField(default=0, null=True)),
                ('weighted_pos', models.FloatField(default=0, null=True)),
                ('neg', models.IntegerField(default=0, null=True)),
                ('weighted_neg', models.FloatField(default=0, null=True)),
                ('score', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('login', models.TextField(default=None, primary_key=True, serialize=False)),
                ('name', models.TextField(default=None, null=True)),
                ('score', models.FloatField(default=0, null=True)),
                ('rank', models.IntegerField(default=None, null=True)),
                ('trend', models.IntegerField(default=None, null=True)),
                ('last_active_at', models.DateTimeField(default=None, null=True)),
                ('pos_in', models.IntegerField(default=0, null=True)),
                ('weighted_pos_in', models.FloatField(default=0, null=True)),
                ('pos_out', models.IntegerField(default=0, null=True)),
                ('neg_in', models.IntegerField(default=0, null=True)),
                ('weighted_neg_in', models.FloatField(default=0, null=True)),
                ('neg_out', models.IntegerField(default=0, null=True)),
                ('punishment', models.FloatField(default=0, null=True)),
                ('weight_factor', models.FloatField(default=0.1, null=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.TextField(default=None, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('content', models.TextField(default=None, null=True)),
                ('giver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='give', to='meta_review.Participant')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receive', to='meta_review.Participant')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meta_review.Comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meta_review.Participant'),
        ),
    ]
