# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='punishment',
            new_name='offset',
        ),
        migrations.AddField(
            model_name='participant',
            name='modified_comments_after_meta_review',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
