# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-11 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=500)),
                ('room', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('sent_by', models.CharField(max_length=300)),
                ('message_type', models.CharField(max_length=100)),
            ],
        ),
    ]
