# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('identifier', models.IntegerField(choices=[(1, 'Coding'), (2, 'User Interface'), (3, 'Documentation & Training'), (4, 'Quality Assurance'), (5, 'Outreach & Research')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('email_id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('url', models.URLField(blank=True)),
                ('summary', models.TextField(default='', max_length=300)),
                ('mentors', models.ManyToManyField(to='gci.Mentor')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramYear',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('program_year', models.ManyToManyField(to='gci.ProgramYear')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1500)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Published')], default=1)),
                ('max_instances', models.IntegerField(default=1)),
                ('is_beginner', models.BooleanField(default=False)),
                ('time_to_complete_in_days', models.IntegerField(default=3)),
                ('external_url', models.URLField()),
                ('metadata', models.TextField()),
                ('last_modified', models.DateField()),
                ('categories', models.ManyToManyField(to='gci.Category')),
                ('mentors', models.ManyToManyField(to='gci.Mentor')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gci.Organization')),
                ('tags', models.ManyToManyField(to='gci.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'CLAIMED'), (2, 'ABANDONED'), (3, 'SUBMITTED'), (4, 'NEEDS_WORK'), (5, 'OUT_OF_TIME'), (6, 'COMPLETED')])),
                ('completion_date', models.DateField()),
                ('deadline', models.DateField()),
                ('modified', models.DateField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gci.Organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gci.Student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gci.Task')),
            ],
        ),
    ]
