# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Getorg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('repository', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('comments', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42)),
                ('org_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='getorgdata.Getorg')),
            ],
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('html_url', models.URLField()),
                ('target_repository', models.CharField(max_length=100)),
                ('source_repository', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('tests_passed', models.BooleanField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('comments', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='author',
            field=models.ManyToManyField(to='getorgdata.User'),
        ),
        migrations.AddField(
            model_name='issue',
            name='assignees',
            field=models.ManyToManyField(to='getorgdata.User'),
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(to='getorgdata.Label'),
        ),
        migrations.AddField(
            model_name='issue',
            name='org',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='getorgdata.Getorg'),
        ),
    ]
