# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-11 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='answers_given',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='ignore_messages',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='questions_asked',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
